Default: &defaults
  database: HBFS.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: HBFS_test.sqlite3
  <<: *defaults

Staging:
  database: HBFS_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: HBFS_production.sqlite3
  poolsize: 100
  <<: *defaults
